SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 830
BACKGROUND_PIC = 'ElevatorChallenge - Python/background.png'

NUM_OF_FLOORS = 20
FLOOR_PIC = 'ElevatorChallenge_2.0/brick_wall.jpg'
FLOOR_WIDTH = 200
FLOOR_HEIGHT = 50
SECONDS_BETWEEN_FLOORS = 0.5
FLOOR_NUMBER_FONT = None
FLOOR_NUMBER_FONT_SIZE = 25
FLOOR_NUMBER_COLOR = 'orange'
FLOOR_MARGIN = 100

GAP_WIDTH = FLOOR_WIDTH
GAP_HEIGHT = 7
GAP_PIC = 'ElevatorChallenge_2.0/gap_pic.png'

BUTTON_WIDTH = 50
BUTTON_HEIGHT = 20

TIMER_WIDTH = 100
TIMER_HEIGHT = 50
TIMER_FONT = None
TIMER_FONT_SIZE = 30
TIMER_FONT_COLOR = "black"
TIMER_MARGIN = 50

NUM_OF_ELEVATORS = 3
ELEVATOR_PIC_UP = 'ElevatorChallenge_2.0/elv.png'
ELEVATOR_PIC_DOWN = 'ElevatorChallenge_2.0/elv.png'
ELEVATOR_WIDTH = 40
ELEVATOR_HEIGHT = 40
PIXELS_BETWEEN_ELEVATOR = 10
ELEVATOR_SOUND = 'ElevatorChallenge_2.0/ding.mp3'

SCROLL_SPEED = 8
